[package]
name = "conflicts_info_parse"
version = "0.1.0"
edition = "2018"

[dependencies]
structopt = "0.3.16"
log = "0.4.0"
env_logger = "0.8.4"
regex = "1.5.4"
csv = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha3 = "0.10"
libsm = "0.4.0"
serde_repr = "0.1"
